# SPDX-License-Identifier: CC0-1.0
# infoware - C++ System information Library

# wait for the day nab gets a GitHub sponsorship
#github: [ThePhD, nabijaczleweli]
patreon: nabijaczleweli
custom: https://www.paypal.me/nabijaczleweli
